### ISSUE TITLE
undefined local variable or method `acts_as_authorized_user'

### ISSUE THREAD

**Issue by jackkinsella** [warrenli/mini-shop#1]
Hi there,

Excited to try your app but having a hiccup

I cloned, updated rails version to 2.3.5, added a database.yml file, rake gems:install (+have latest authlogic) but I get this error when I try to migrate.

Any ideas?

**Comment by warrenli** [comment]
Need to install some plugins before migrate

git submodule init
git submodule update

**Comment by jackkinsella** [comment]
works perfectly thanks!
